# -*- coding: utf-8 -*-
"""Aradhna python project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f-AMdbJNwmcB5jBwPVa44O55t1U5lbnn
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from google.colab import files
uploaded = files.upload()
df=pd.read_csv('Superstore_5000.csv')
df.head()

"""# **data set information**"""

print(df.info())

print(df.describe())

print(df.isnull().sum())

"""# **Highest sales category**"""

Highest_sales_category=df.groupby('Category')['Sales'].sum().sort_values(ascending=False)
print("Highest_sales_category")
print(Highest_sales_category)

plt.figure(figsize=(7,5))
Highest_sales_category.plot(kind='bar')
plt.xlabel('Category')
plt.ylabel('Total Sales')
plt.title('Total Sales by Category')
plt.show()

"""# **Highest profit region**"""

Highest_profit_region=df.groupby('Region')['Profit'].sum().sort_values(ascending=False)
print("Highest profit region")
print(Highest_profit_region)

plt.figure(figsize=(7,5))
Highest_profit_region.plot(kind='bar')
plt.title('Profit by region')
plt.xlabel('Region')
plt.ylabel('Total Profit')
plt.show()

"""# **Sales V/S profit relationship**"""

Correlation=df['Sales'].corr(df['Profit'])
print("Correlation between sales and profit",Correlation)

"""scatter plot"""

plt.figure(figsize=(7,5))
plt.scatter(df['Sales'],df['Profit'])
plt.title('Sales V/S Profit relationship')
plt.xlabel('Sales')
plt.ylabel('Profit')
plt.show()

"""heatmap"""

corr_matrix = df[['Sales', 'Profit', 'Quantity']].corr()

plt.figure(figsize=(6,4))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""# **Generate bussiness insights**"""

print("Business Insights")
print("-------------------")

print("1. Office Supplies category has the highest sales.")
print("2. North region generates the highest profit.")
print("3. Higher sales do not always mean higher profit.")
print("4. Sales and Profit have weak positive correlation.")
print("5. Focus more on profitable products and regions.")

"""# **Business Questions Answered**
**1. Which category performs best?**

Office Supplies category performs best in terms of sales.

**2. Which region generates highest sales/profit?**

North region generates the highest profit.

**3. Does higher sales always mean higher profit?**

No, higher sales do not always guarantee higher profit.

**4. Which variables are strongly correlated?**

Sales and Profit show weak positive correlation.

**5. What business recommendations can be given?**

*   Reduce losses in low-profit products
*   Increase marketing for high-sales products.
*  focus on profitable regions.
*  Improve low_performing categories.
"""

df.to_csv('Superstore_5000.csv', index=False)

from google.colab import files

df.to_csv('Sales_Data.csv', index=False)

files.download('Sales_Data.csv')